version: '3.4'
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server
        container_name: yogadbserver
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password123
        ports:
            - "1433:1433"
        volumes: 
            - yogaappvolume:/yogadb

volumes: 
    yogaappvolume:


# Befehl zum ausführen: docker-compose up